### ISSUE TITLE
Add docker image run command specifications to documentation

### ISSUE THREAD

**Issue by DeniseSl22** [marvinm2/WikiPathwaysLoader#16]
See https://github.com/ammar257ammar/virtuoso-httpd-docker as example.

**Comment by DeniseSl22** [comment]
And make sure to add a persistent volume in the Docker, so that the data does not need to be reloaded when the docker is stopped and started again. Example:

```
-v PATH_TO_VIRTUOSO_DATA_FOLDER:/data \
-v PATH_TO_VIRTUOSO_IMPORT_FOLDER:/import \
```

**Comment by DeniseSl22** [comment]
And add a persistent volume for the void header file iso:
```
cp ../import/void ../usr/local/apache2/htdocs/.well-known/
```

**Comment by DeniseSl22** [comment]
Current fix for http https:

Do the docker exec command just like the last step in the loading protocol (for the void header file)
Then you should navigate to the snorql.js, where this URL is located. The snorql.js is in /assets/js/ , which is in the same location as the void file (but one level up)

Just do an edit of the snorql.js (very much at the top of that file) and add the 's'

```
cd /usr/local/apache2/htdocs/assets/js/
nano snorql.js
```

**Comment by marvinm2** [comment]
The README.md now contains documentation on restarting the service with docker-compose. HTTPS issue is resolved, void copying is documented, persistent volume for db mapped so a downed service can be started back up without issue of losing data

However:
This repository does not contain the main setup documentation (and not the Docker image). I will file a issue for that here: https://github.com/wikipathways/snorql-extended. That repo is a fork from: https://github.com/ammar257ammar/Snorql-UI
