### ISSUE TITLE
Update docker to most recent version

### ISSUE THREAD

**Issue by DeniseSl22** [marvinm2/WikiPathwaysLoader#17]
Version 7.2.10 is [most recent](https://github.com/openlink/virtuoso-opensource/issues/734), we are currently deploying: Version 7.2.5.3229-pthreads as of Aug 21 2019 (000000)

This might be related to this issue, where a service federated query could break the endpoint:
https://github.com/openlink/virtuoso-opensource/issues/734

**Comment by DeniseSl22** [comment]
Response:

The patch discussed here was committed in Dec 2018, and the next VOS shipped was [Release 7.2.6 (almost immediately replaced by 7.2.6.1)](https://github.com/openlink/virtuoso-opensource/releases/tag/v7.2.6.1). As usual, we would recommend that you update to the latest available, which is currently [Release 7.2.10](https://github.com/openlink/virtuoso-opensource/releases/tag/v7.2.10).

Please confirm the version (7.2.6.1 or later) to which you have updated, and whether you continue to see the issue described here with that update, so we may close the issue, or dig into what other cause there may be. If you're uncertain what version you're now running, the virtuoso-t -? command or [this SPARQL query](https://vos.openlinksw.com/owiki/wiki/VOS/VirtCheckSvrVersionViaSparql) may be used to discover the version details.

**Comment by egonw** [comment]
See also https://github.com/ammar257ammar/virtuoso-httpd-docker/issues/3

**Comment by marvinm2** [comment]
The main repo covers the virtuoso versions. This branch is synchronised
